//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "company_interventions")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub company_id: i32,
  pub practitioner_id: i32,
  pub quantity: i32,
  pub unit_price_in_cents: i32,
  #[sea_orm(column_type = "Decimal(Some((4, 1)))")]
  pub vat_rate_in_percent: Decimal,
  pub issue_date: Date,
  pub object: String,
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
  #[sea_orm(belongs_to, from = "company_id", to = "id", on_update = "NoAction", on_delete = "Cascade")]
  pub practitioner_companies: HasOne<super::practitioner_companies::Entity>,
  #[sea_orm(
    belongs_to,
    from = "practitioner_id",
    to = "id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  pub users: HasOne<super::users::Entity>,
}
