//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use chrono::Utc;
use sea_orm::{entity::prelude::*, ActiveValue};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "company_interventions")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub company_id: i32,
  pub practitioner_id: i32,
  pub quantity: i32,
  pub unit_price_in_cents: i32,
  #[sea_orm(column_type = "Decimal(Some((4, 1)))")]
  pub vat_rate_in_percent: Decimal,
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::practitioner_companies::Entity",
    from = "Column::CompanyId",
    to = "super::practitioner_companies::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  PractitionerCompanies,
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::PractitionerId",
    to = "super::users::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Users,
}

impl Related<super::practitioner_companies::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::PractitionerCompanies.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
  async fn before_save<C>(self, _db: &C, insert: bool) -> Result<Self, DbErr>
  where
    C: ConnectionTrait,
  {
    if !insert && self.updated_at.is_unchanged() {
      let mut this = self;
      this.updated_at = ActiveValue::Set(Utc::now().into());
      Ok(this)
    } else {
      Ok(self)
    }
  }
}
