//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::PaymentMethod;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "medical_appointments")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub user_id: i32,
  pub patient_id: i32,
  pub practitioner_office_id: i32,
  pub date: Date,
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
  pub price_in_cents: i32,
  pub payment_method: Option<PaymentMethod>,
  #[sea_orm(belongs_to, from = "patient_id", to = "id", on_update = "Cascade", on_delete = "Cascade")]
  pub patients: HasOne<super::patients::Entity>,
  #[sea_orm(
    belongs_to,
    from = "practitioner_office_id",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub practitioner_offices: HasOne<super::practitioner_offices::Entity>,
  #[sea_orm(belongs_to, from = "user_id", to = "id", on_update = "Cascade", on_delete = "Cascade")]
  pub users: HasOne<super::users::Entity>,
}
