//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod company_interventions;
pub mod medical_appointments;
pub mod patients;
pub mod practitioner_companies;
pub mod practitioner_offices;
pub mod sea_orm_active_enums;
pub mod user_business_informations;
pub mod user_practitioner_offices;
pub mod users;
