//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "patients")]
pub struct Model {
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
  #[sea_orm(primary_key)]
  pub id: i32,
  pub ssn: Option<String>,
  #[sea_orm(unique)]
  pub pid: Uuid,
  pub hashed_ssn: Option<String>,
  pub first_name: String,
  pub last_name: String,
  pub address_line_1: String,
  pub address_zip_code: String,
  pub address_city: String,
  pub address_country: String,
  pub email: Option<String>,
  pub user_id: i32,
  #[sea_orm(has_many)]
  pub medical_appointments: HasMany<super::medical_appointments::Entity>,
  #[sea_orm(belongs_to, from = "user_id", to = "id", on_update = "Cascade", on_delete = "Cascade")]
  pub users: HasOne<super::users::Entity>,
}
