//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "patients")]
pub struct Model {
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
  #[sea_orm(primary_key)]
  pub id: i32,
  pub ssn: String,
  #[sea_orm(unique)]
  pub pid: Uuid,
  pub hashed_ssn: String,
  pub first_name: String,
  pub last_name: String,
  pub address_line_1: String,
  pub address_zip_code: String,
  pub address_city: String,
  pub address_country: String,
  pub email: Option<String>,
  pub user_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::medical_appointments::Entity")]
  MedicalAppointments,
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::UserId",
    to = "super::users::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Users,
}

impl Related<super::medical_appointments::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::MedicalAppointments.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}
