//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "practitioner_offices")]
pub struct Model {
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
  #[sea_orm(primary_key)]
  pub id: i32,
  pub name: String,
  pub address_line_1: String,
  pub address_zip_code: String,
  pub address_city: String,
  pub address_country: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::medical_appointments::Entity")]
  MedicalAppointments,
  #[sea_orm(has_many = "super::user_practitioner_offices::Entity")]
  UserPractitionerOffices,
}

impl Related<super::medical_appointments::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::MedicalAppointments.def()
  }
}

impl Related<super::user_practitioner_offices::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserPractitionerOffices.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    super::user_practitioner_offices::Relation::Users.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::user_practitioner_offices::Relation::PractitionerOffices.def().rev())
  }
}
