//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "practitioner_offices")]
pub struct Model {
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
  #[sea_orm(primary_key)]
  pub id: i32,
  pub name: String,
  pub address_line_1: String,
  pub address_zip_code: String,
  pub address_city: String,
  pub address_country: String,
  #[sea_orm(has_many)]
  pub medical_appointments: HasMany<super::medical_appointments::Entity>,
  #[sea_orm(has_many, via = "user_practitioner_offices")]
  pub users: HasMany<super::users::Entity>,
}
