//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "practitioner_companies")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub name: String,
  pub contact_name: String,
  pub siret: Option<String>,
  pub contact_email: String,
  pub address_line_1: Option<String>,
  pub address_zip_code: Option<String>,
  pub address_city: Option<String>,
  pub address_country: Option<String>,
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
  pub user_id: i32,
  #[sea_orm(has_many)]
  pub company_interventions: HasMany<super::company_interventions::Entity>,
  #[sea_orm(belongs_to, from = "user_id", to = "id", on_update = "NoAction", on_delete = "Cascade")]
  pub users: HasOne<super::users::Entity>,
}
