//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

pub use super::company_interventions::Entity as CompanyInterventions;
pub use super::medical_appointments::Entity as MedicalAppointments;
pub use super::patients::Entity as Patients;
pub use super::practitioner_companies::Entity as PractitionerCompanies;
pub use super::practitioner_offices::Entity as PractitionerOffices;
pub use super::user_business_informations::Entity as UserBusinessInformations;
pub use super::user_practitioner_offices::Entity as UserPractitionerOffices;
pub use super::users::Entity as Users;
