//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "payment_method")]
pub enum PaymentMethod {
  #[sea_orm(string_value = "card")]
  Card,
  #[sea_orm(string_value = "cash")]
  Cash,
  #[sea_orm(string_value = "check")]
  Check,
  #[sea_orm(string_value = "transfer")]
  Transfer,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "profession")]
pub enum Profession {
  #[sea_orm(string_value = "general_practitioner")]
  GeneralPractitioner,
  #[sea_orm(string_value = "pediatrician")]
  Pediatrician,
  #[sea_orm(string_value = "gynecologist")]
  Gynecologist,
  #[sea_orm(string_value = "psychiatrist")]
  Psychiatrist,
  #[sea_orm(string_value = "gastroenterologist")]
  Gastroenterologist,
  #[sea_orm(string_value = "ent_specialist")]
  EntSpecialist,
  #[sea_orm(string_value = "endocrinologist")]
  Endocrinologist,
  #[sea_orm(string_value = "cardiologist")]
  Cardiologist,
  #[sea_orm(string_value = "angiologist")]
  Angiologist,
  #[sea_orm(string_value = "nephrologist")]
  Nephrologist,
  #[sea_orm(string_value = "neurologist")]
  Neurologist,
  #[sea_orm(string_value = "pulmonologist")]
  Pulmonologist,
  #[sea_orm(string_value = "rheumatologist")]
  Rheumatologist,
  #[sea_orm(string_value = "dermatologist")]
  Dermatologist,
  #[sea_orm(string_value = "dentist")]
  Dentist,
  #[sea_orm(string_value = "midwife")]
  Midwife,
  #[sea_orm(string_value = "physiotherapist")]
  Physiotherapist,
  #[sea_orm(string_value = "nurse")]
  Nurse,
  #[sea_orm(string_value = "psychologist")]
  Psychologist,
  #[sea_orm(string_value = "osteopath")]
  Osteopath,
  #[sea_orm(string_value = "audiologist")]
  Audiologist,
  #[sea_orm(string_value = "chiropractor")]
  Chiropractor,
  #[sea_orm(string_value = "genetic_counselor")]
  GeneticCounselor,
  #[sea_orm(string_value = "dietitian")]
  Dietitian,
  #[sea_orm(string_value = "occupational_therapist")]
  OccupationalTherapist,
  #[sea_orm(string_value = "speech_therapist")]
  SpeechTherapist,
  #[sea_orm(string_value = "orthoptist")]
  Orthoptist,
  #[sea_orm(string_value = "podiatrist")]
  Podiatrist,
  #[sea_orm(string_value = "psychomotrician")]
  Psychomotrician,
  #[sea_orm(string_value = "psychotherapist")]
  Psychotherapist,
}
