//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::Profession;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_business_informations")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub adeli_number: Option<String>,
  pub rpps_number: String,
  pub siret_number: String,
  #[sea_orm(unique)]
  pub user_id: i32,
  pub signature_file_name: Option<String>,
  pub profession: Profession,
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
  pub beneficiary_name: Option<String>,
  pub iban: Option<String>,
  pub bic: Option<String>,
  #[sea_orm(belongs_to, from = "user_id", to = "id", on_update = "Cascade", on_delete = "Cascade")]
  pub users: HasOne<super::users::Entity>,
}
