//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
  #[sea_orm(primary_key)]
  pub id: i32,
  pub pid: Uuid,
  #[sea_orm(unique)]
  pub email: String,
  pub password: String,
  pub phone_number: String,
  pub first_name: String,
  pub last_name: String,
  pub access_key: Option<String>,
  pub is_access_key_verified: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::company_interventions::Entity")]
  CompanyInterventions,
  #[sea_orm(has_many = "super::medical_appointments::Entity")]
  MedicalAppointments,
  #[sea_orm(has_many = "super::patients::Entity")]
  Patients,
  #[sea_orm(has_many = "super::practitioner_companies::Entity")]
  PractitionerCompanies,
  #[sea_orm(has_one = "super::user_business_informations::Entity")]
  UserBusinessInformations,
  #[sea_orm(has_many = "super::user_practitioner_offices::Entity")]
  UserPractitionerOffices,
}

impl Related<super::company_interventions::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::CompanyInterventions.def()
  }
}

impl Related<super::medical_appointments::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::MedicalAppointments.def()
  }
}

impl Related<super::patients::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Patients.def()
  }
}

impl Related<super::practitioner_companies::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::PractitionerCompanies.def()
  }
}

impl Related<super::user_business_informations::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserBusinessInformations.def()
  }
}

impl Related<super::user_practitioner_offices::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserPractitionerOffices.def()
  }
}

impl Related<super::practitioner_offices::Entity> for Entity {
  fn to() -> RelationDef {
    super::user_practitioner_offices::Relation::PractitionerOffices.def()
  }
  fn via() -> Option<RelationDef> {
    Some(
      super::user_practitioner_offices::Relation::Users
        .def()
        .rev(),
    )
  }
}
