//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_practitioner_offices")]
pub struct Model {
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
  #[sea_orm(primary_key, auto_increment = false)]
  pub user_id: i32,
  #[sea_orm(primary_key, auto_increment = false)]
  pub practitioner_office_id: i32,
  #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
  pub revenue_share_percentage: Decimal,
  #[sea_orm(
    belongs_to,
    from = "practitioner_office_id",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub practitioner_offices: HasOne<super::practitioner_offices::Entity>,
  #[sea_orm(belongs_to, from = "user_id", to = "id", on_update = "Cascade", on_delete = "Cascade")]
  pub users: HasOne<super::users::Entity>,
}
