//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use super::sea_orm_active_enums::Profession;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_business_informations")]
pub struct Model {
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
  #[sea_orm(primary_key)]
  pub id: i32,
  pub adeli_number: Option<String>,
  pub rpps_number: String,
  pub siret_number: String,
  #[sea_orm(unique)]
  pub user_id: i32,
  pub signature_file_name: Option<String>,
  pub profession: Profession,
  pub beneficiary_name: Option<String>,
  pub iban: Option<String>,
  pub bic: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::UserId",
    to = "super::users::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Users,
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}
