//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  #[sea_orm(unique)]
  pub pid: Uuid,
  #[sea_orm(unique)]
  pub email: String,
  pub password: String,
  pub phone_number: String,
  pub first_name: String,
  pub last_name: String,
  pub access_key: Option<String>,
  pub is_access_key_verified: bool,
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
  #[sea_orm(has_many)]
  pub company_interventions: HasMany<super::company_interventions::Entity>,
  #[sea_orm(has_many)]
  pub medical_appointments: HasMany<super::medical_appointments::Entity>,
  #[sea_orm(has_many)]
  pub patients: HasMany<super::patients::Entity>,
  #[sea_orm(has_many)]
  pub practitioner_companies: HasMany<super::practitioner_companies::Entity>,
  #[sea_orm(has_one)]
  pub user_business_informations: HasOne<super::user_business_informations::Entity>,
  #[sea_orm(has_many)]
  pub user_practitioner_offices: HasMany<super::user_practitioner_offices::Entity>,
}
